### Marital Satisfaction Data Cleaning

In [4]:
import pandas as pd
from IPython.display import display

In [6]:
df = pd.read_csv("Marital.csv")
df.head()

,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)","Religiosity (1-not religious at all, 7-extremely religious)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Item number,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,21.0,22.0,1,2.0,3.0,4.0,1,2.0,3.0,4.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,National level,NaN,NaN,NaN,Individual level,NaN,NaN,NaN
2,Brazil,1.0,21.0,2.0,0.0,0.0,5.0,3.0,1.0,4.0,...,7.0,7.0,1,1.0,1.0,1.0,1,1.0,1.0,1.0
3,Brazil,1.0,29.0,3.0,1.0,0.0,5.0,3.0,1.0,6.0,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
4,Brazil,1.0,30.0,7.0,0.0,0.0,5.0,3.0,1.0,4.0,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0

In [8]:
df.shape

(7180, 31)

In [10]:
df.tail()

,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)","Religiosity (1-not religious at all, 7-extremely religious)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
7175,Uganda,1.0,32.0,7.0,2.0,3.0,5.0,1.0,10.0,4.0,...,5.0,5.0,2,2.0,2.0,7.0,2,2.0,2.0,7.0
7176,Uganda,1.0,36.0,6.0,4.0,4.0,5.0,3.0,NaN,4.0,...,6.0,6.0,2,2.0,2.0,3.0,3,2.0,1.0,1.0
7177,Uganda,1.0,32.0,2.0,1.0,1.0,5.0,2.0,NaN,7.0,...,7.0,7.0,1,1.0,4.0,2.0,1,2.0,4.0,2.0
7178,Uganda,1.0,27.0,3.0,2.0,2.0,5.0,2.0,NaN,7.0,...,7.0,6.0,1,2.0,3.0,4.0,3,3.0,2.0,3.0
7179,Uganda,1.0,53.0,24.0,6.0,1.0,5.0,3.0,NaN,6.0,...,5.0,5.0,1,1.0,2.0,3.0,1,1.0,2.0,5.0

In [12]:
df.columns

Index(['Country ', 'Sex (1-M, 2-F)', 'Age', 'Marriage duration (years)',
       'Number of children', 'Number of brought up children',
       'Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree) ',
       'Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)',
       'Religion (1-Protestant, 2-Catholic,  3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism) ',
       'Religiosity (1-not religious at all, 7-extremely religious)',
       'Pension (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)',
       'Marriage and Relationships Questionnaire (MRQ) (1-yes, 3-neither yes nor no, 5-no)',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Kansas Marital Satisfaction Scale (KMSS) (1-very dissatisfied, 7-very satisfied)',
       'Unnamed: 21', 'Unnamed: 22',
       'Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30'],
      dtype='object')

In [14]:
df.to_csv("Cleaning2.csv")

In [16]:
df2 = pd.read_csv("Cleaning2.csv")
df2.head()

,Unnamed: 0,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,0,Item number,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,21.0,22.0,1,2.0,3.0,4.0,1,2.0,3.0,4.0
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,National level,NaN,NaN,NaN,Individual level,NaN,NaN,NaN
2,2,Brazil,1.0,21.0,2.0,0.0,0.0,5.0,3.0,1.0,...,7.0,7.0,1,1.0,1.0,1.0,1,1.0,1.0,1.0
3,3,Brazil,1.0,29.0,3.0,1.0,0.0,5.0,3.0,1.0,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
4,4,Brazil,1.0,30.0,7.0,0.0,0.0,5.0,3.0,1.0,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0

In [18]:
df.iloc[[9]]

,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)","Religiosity (1-not religious at all, 7-extremely religious)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
9,Brazil,1.0,40.0,20.0,2.0,2.0,5.0,3.0,1.0,7.0,...,7.0,7.0,6,5.0,4.0,3.0,1,1.0,4.0,1.0

In [20]:
df.iloc[4:7]

,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)","Religiosity (1-not religious at all, 7-extremely religious)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
4,Brazil,1.0,30.0,7.0,0.0,0.0,5.0,3.0,1.0,4.0,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0
5,Brazil,1.0,30.0,7.0,1.0,1.0,5.0,3.0,1.0,6.0,...,6.0,6.0,3,1.0,1.0,2.0,1,1.0,1.0,1.0
6,Brazil,1.0,28.0,9.0,0.0,0.0,4.0,2.0,1.0,5.0,...,6.0,7.0,3,2.0,3.0,2.0,1,1.0,1.0,1.0

In [22]:
df.iloc[1:9:2]

,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)","Religiosity (1-not religious at all, 7-extremely religious)",...,Unnamed: 21,Unnamed: 22,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)",Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,National level,NaN,NaN,NaN,Individual level,NaN,NaN,NaN
3,Brazil,1.0,29.0,3.0,1.0,0.0,5.0,3.0,1.0,6.0,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
5,Brazil,1.0,30.0,7.0,1.0,1.0,5.0,3.0,1.0,6.0,...,6.0,6.0,3,1.0,1.0,2.0,1,1.0,1.0,1.0
7,Brazil,1.0,39.0,9.0,1.0,0.0,5.0,3.0,1.0,6.0,...,6.0,5.0,3,1.0,5.0,3.0,1,1.0,3.0,1.0

In [24]:
df[["Age"]].head()

    Age
0   2.0
1   NaN
2  21.0
3  29.0
4  30.0

In [26]:
print(df['Age'].sum())
print(df['Age'].mean())
print(df['Age'].max())
print(df['Age'].min())
print(df['Age'].idxmax())
print(df['Age'].idxmin())

291895.5
40.65963226076055
88.0
2.0
2560
0

In [28]:
df.dtypes

Country                                                                                                                                                                                                              object
Sex (1-M, 2-F)                                                                                                                                                                                                      float64
Age                                                                                                                                                                                                                 float64
Marriage duration (years)                                                                                                                                                                                           float64
Number of children                                                                                                                                                                                                  float64
Number of brought up children                                                                                                                                                                                       float64
Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)                                                                            float64
Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)    float64
Religion (1-Protestant, 2-Catholic,  3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)                                            float64
Religiosity (1-not religious at all, 7-extremely religious)                                                                                                                                                         float64
Pension (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)                                                                                                                                       float64
Marriage and Relationships Questionnaire (MRQ) (1-yes, 3-neither yes nor no, 5-no)                                                                                                                                  float64
Unnamed: 12                                                                                                                                                                                                         float64
Unnamed: 13                                                                                                                                                                                                         float64
Unnamed: 14                                                                                                                                                                                                         float64
Unnamed: 15                                                                                                                                                                                                         float64
Unnamed: 16                                                                                                                                                                                                         float64
Unnamed: 17                                                                                                                                                                                                         float64
Unnamed: 18                                                                                                                                                                                                         float64
Unnamed: 19                                                                                                                                                                                                         float64
Kansas Marital Satisfaction Scale (KMSS) (1-very dissatisfied, 7-very satisfied)                                                                                                                                    float64
Unnamed: 21                                                                                                                                                                                                         float64
Unnamed: 22                                                                                                                                                                                                         float64
Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)                                                                                                      object
Unnamed: 24                                                                                                                                                                                                         float64
Unnamed: 25                                                                                                                                                                                                         float64
Unnamed: 26                                                                                                                                                                                                         float64
Unnamed: 27                                                                                                                                                                                                          object
Unnamed: 28                                                                                                                                                                                                         float64
Unnamed: 29                                                                                                                                                                                                         float64
Unnamed: 30                                                                                                                                                                                                         float64
dtype: object

In [30]:
#Show only rows that contain at least one emoty (NaN) value
empty_rows = df[df.isnull().any(axis=1)]
print(empty_rows.to_string())

         Country   Sex (1-M, 2-F)   Age  Marriage duration (years)  Number of children  Number of brought up children  Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree)   Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country)  Religion (1-Protestant, 2-Catholic,  3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism)   Religiosity (1-not religious at all, 7-extremely religious)  Pension (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)  Marriage and Relationships Questionnaire (MRQ) (1-yes, 3-neither yes nor no, 5-no)  Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  Kansas Marital Satisfaction Scale (KMSS) (1-very dissatisfied, 7-very satisfied)  Unnamed: 21  Unnamed: 22 Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree)  Unnamed: 24  Unnamed: 25  Unnamed: 26       Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30
1             NaN             NaN   NaN                        NaN                 NaN                            NaN                                                                                                                                        NaN                                                                                                                                                                                                               NaN                                                                                                                                                                        NaN                                                          NaN                                                                            NaN                                                                                 NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN                                                                               NaN          NaN          NaN                                                                                                  National level          NaN          NaN          NaN  Individual level          NaN          NaN          NaN
378       Brazil              1.0  33.0                       5.00                 2.0                            2.0                                                                                                                                        3.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          4.0                                                                            6.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          2.0          1.0                                                                               7.0          7.0          7.0                                                                                                               1          3.0          1.0          1.0                 1          1.0          1.0          1.0
379       Brazil              1.0  37.0                      18.00                 2.0                            3.0                                                                                                                                        2.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          6.0                                                                            2.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          1.0          1.0                                                                               7.0          7.0          7.0                                                                                                               2          2.0          2.0          3.0                 2          2.0          1.0          1.0
380       Brazil              2.0  23.0                       2.00                 0.0                            0.0                                                                                                                                        5.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          1.0                                                                            1.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          1.0          1.0                                                                               7.0          7.0          7.0                                                                                                               6          6.0          5.0          7.0                 7          7.0          6.0          6.0
381       Brazil              1.0  35.0                      10.00                 2.0                            0.0                                                                                                                                        4.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          5.0                                                                            3.0                                                                                 3.0          1.0          4.0          2.0          2.0          1.0          2.0          6.0          2.0                                                                               4.0          3.0          4.0                                                                                                               2          1.0          3.0          7.0                 7          7.0          7.0          7.0
382       Brazil              2.0  47.0                       7.00                 1.0                            0.0                                                                                                                                        5.0                                                                                                                                                                                                               1.0                                                                                                                                                                        NaN                                                          1.0                                                                            7.0                                                                                 1.0          2.0          1.0          1.0          1.0          1.0          1.0          1.0          1.0                                                                               7.0          7.0          7.0                                                                                                               6          7.0          7.0          7.0                 7          7.0          7.0          7.0
1382      Croatia             1.0  72.0                      47.00                 2.0                            0.0                                                                                                                                        3.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          1.0                                                                            3.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          5.0          1.0                                                                               7.0          7.0          7.0                                                                                                               1          2.0          2.0          3.0                 1          2.0          1.0          1.0
1383      Croatia             2.0  51.0                      29.00                 2.0                            0.0                                                                                                                                        4.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          4.0                                                                            7.0                                                                                 2.0          2.0          2.0          2.0          2.0          2.0          2.0          2.0          2.0                                                                               3.0          3.0          3.0                                                                                                               3          3.0          6.0          5.0                 3          3.0          6.0          6.0
1515      Estonia             1.0  46.0                      23.00                 2.0                            1.0                                                                                                                                        5.0                                                                                                                                                                                                               2.0                                                                                                                                                                        NaN                                                          3.0                                                                            2.0                                                                                 1.0          2.0          1.0          2.0          1.0          2.0          1.0          2.0          1.0                                                                               6.0          6.0          5.0                                                                                                               4          2.0          3.0          3.0                 1          1.0          1.0          1.0
1516      Estonia             2.0  30.0                      10.00                 1.0                            1.0                                                                                                                                        5.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          1.0                                                                            7.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          2.0          1.0                                                                               7.0          6.0          7.0                                                                                                               7          1.0          7.0          1.0                 1          1.0          3.0          1.0
1517      Estonia             2.0  69.0                      43.00                 2.0                            0.0                                                                                                                                        5.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          4.0                                                                            3.0                                                                                 2.0          2.0          3.0          2.0          3.0          1.0          3.0          3.0          2.0                                                                               5.0          5.0          5.0                                                                                                               2          1.0          4.0          2.0                 1          1.0          6.0          1.0
1518      Estonia             1.0  48.0                       1.00                 1.0                            2.0                                                                                                                                        4.0                                                                                                                                                                                                               4.0                                                                                                                                                                        NaN                                                          1.0                                                                            7.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          2.0          1.0                                                                               6.0          7.0          7.0                                                                                                               4          1.0          5.0          7.0                 6          1.0          6.0          1.0
1519      Estonia             2.0  42.0                      21.00                 2.0                            2.0                                                                                                                                        5.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          2.0                                                                            7.0                                                                                 2.0          1.0          1.0          1.0          1.0          2.0          1.0          2.0          1.0                                                                               5.0          6.0          2.0                                                                                                               3          1.0          2.0          1.0                 1          1.0          7.0          1.0
1520      Estonia             2.0  29.0                       4.00                 1.0                            1.0                                                                                                                                        5.0                                                                                                                                                                                                               3.0                                                                                                                                                                        NaN                                                          4.0                                                                            7.0                                                                                 1.0          1.0          1.0          1.0          1.0          1.0          1.0          2.0          1.0                                                                               6.0          6.0          6.0                                                                                                               6          2.0          7.0          2.0                 2          1.0          2.0          2.0

In [47]:
# load without headers to inspect the top rows
df_raw = pd.read_csv("Marital.csv", header=None)

#show the first 10 rows to understand the structure
df_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Country,"Sex (1-M, 2-F)",Age,Marriage duration (years),Number of children,Number of brought up children,"Education (1-no formal education, 2-primary sc...",Material status (1-much better than average in...,"Religion (1-Protestant, 2-Catholic, 3-Jewish,...","Religiosity (1-not religious at all, 7-extreme...",...,NaN,NaN,Collectivism-Individualism (GLOBE survey) (1-s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Item number,1,2,3,4,5,6,7,8,9,...,21.0,22.0,1,2.0,3.0,4.0,1,2.0,3.0,4.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,National level,NaN,NaN,NaN,Individual level,NaN,NaN,NaN
3,Brazil,1,21,2,0,0,5,3,1,4,...,7.0,7.0,1,1.0,1.0,1.0,1,1.0,1.0,1.0
4,Brazil,1,29,3,1,0,5,3,1,6,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
5,Brazil,1,30,7,0,0,5,3,1,4,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0
6,Brazil,1,30,7,1,1,5,3,1,6,...,6.0,6.0,3,1.0,1.0,2.0,1,1.0,1.0,1.0
7,Brazil,1,28,9,0,0,4,2,1,5,...,6.0,7.0,3,2.0,3.0,2.0,1,1.0,1.0,1.0
8,Brazil,1,39,9,1,0,5,3,1,6,...,6.0,5.0,3,1.0,5.0,3.0,1,1.0,3.0,1.0
9,Brazil,1,30,7,2,2,5,3,1,5,...,4.0,4.0,2,1.0,5.0,3.0,2,2.0,3.0,1.0

In [49]:
row_0 = df_raw.iloc[0] # Original names (may be long/incomplete)
row_2 = df_raw.iloc[2] # Category headers ("national level", etc.)

# Fill missing row_0 values with placeholders to avoid NaNs
row_0_filled = row_0.fillna("Unknown")

# Same for row_2 (in case some are empty)
row_2_filled = row_2.fillna("")

#Combine the two with hyphen (or underscore if preferred)
combined_headers = row_0_filled + " - " + row_2_filled

In [51]:
df = df_raw.iloc[3:].copy()
df.columns = combined_headers
df.reset_index(drop=True, inplace=True)

In [53]:
df.head()

,Country -,"Sex (1-M, 2-F) -",Age -,Marriage duration (years) -,Number of children -,Number of brought up children -,"Education (1-no formal education, 2-primary school, 3-secondary school, 4-high school or technical college, 5-bachelor or master degree) -","Material status (1-much better than average in my country, 2-better than average in my country, 3-similar to average in my country, 4-worse than average in my country, 5-much worse than average in my country) -","Religion (1-Protestant, 2-Catholic, 3-Jewish, 4-Muslim, 5-Buddhist, 6-None, 7-Jehovah, 8-Evangelic, 9-Spiritualism, 10-Other - very specific, 11-Orthodox, 12-Hinduism) -","Religiosity (1-not religious at all, 7-extremely religious) -",...,Unknown -,Unknown -,"Collectivism-Individualism (GLOBE survey) (1-strongly agree, 4-neither agree nor disagree, 7-strongly disagree) - National level",Unknown -,Unknown -,Unknown -,Unknown - Individual level,Unknown -,Unknown -,Unknown -
0,Brazil,1,21,2,0,0,5,3,1,4,...,7.0,7.0,1,1.0,1.0,1.0,1,1.0,1.0,1.0
1,Brazil,1,29,3,1,0,5,3,1,6,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
2,Brazil,1,30,7,0,0,5,3,1,4,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0
3,Brazil,1,30,7,1,1,5,3,1,6,...,6.0,6.0,3,1.0,1.0,2.0,1,1.0,1.0,1.0
4,Brazil,1,28,9,0,0,4,2,1,5,...,6.0,7.0,3,2.0,3.0,2.0,1,1.0,1.0,1.0